name: Workflow test
on: 
  pull_request:
    types: [labeled]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update PR description
        uses: nefrob/pr-description@v1.0.0
        with:
          content: "new output"
          token: ${{ secrets.GITHUB_TOKEN }}
