name: Workflow test
on: 
  push:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update PR description
        uses: nefrob/pr-description@nefrob/push-events-handling
        with:
          content: "new output"
          token: ${{ secrets.GITHUB_TOKEN }}
