name: Workflow test
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create code coverage summary
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both
      - name: Update PR description
        uses: nefrob/pr-description@v0.1.0
        with:
          content: code-coverage-results.md
          contentIsFilePath: true
          token: ${{ secrets.GITHUB_TOKEN }}
