name: Workflow test
on: 
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update PR description
        uses: nefrob/pr-description@master
        with:
          content: "${{ github.event.pull_request.body }}\n\nSome additional text"
          token: ${{ secrets.GITHUB_TOKEN }}
