name: Workflow test
on: 
  pull_request:
  push:

env:
  MY_VAR: 123

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update PR description
        uses: nefrob/pr-description@nefrob/bump-nodejs-to-latest-lts
        with:
          content: "\n\n${{ env.MY_VAR }}\n\nSome additional text node20"
          token: ${{ secrets.GITHUB_TOKEN }}
